basePath: /api/v1
definitions:
  github_com_rytsh_fine_internal_server_msg.WebApiError:
    properties:
      error:
        example: problem explanation
        type: string
    type: object
  github_com_rytsh_fine_internal_server_msg.WebApiSuccess:
    properties:
      msg:
        example: success
        type: string
    type: object
info:
  contact:
    email: eates23@gmail.com
    name: Eray Ates
  description: file management service
  title: fine API
  version: "1.0"
paths:
  /file:
    delete:
      description: Delete file from server by path. Delete directory with force set
        to true.
      parameters:
      - description: file path in server
        in: query
        name: path
        required: true
        type: string
      - description: force delete
        in: query
        name: force
        type: boolean
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
      summary: Delete File
      tags:
      - file
    get:
      description: Get File
      parameters:
      - description: file path in server
        in: query
        name: path
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: file
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
      summary: Get File
      tags:
      - file
    post:
      consumes:
      - multipart/form-data
      description: Post File
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      - description: file path in server
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
      summary: Post File
      tags:
      - file
    put:
      consumes:
      - multipart/form-data
      description: Put File
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      - description: file path in server
        in: query
        name: path
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiSuccess'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/github_com_rytsh_fine_internal_server_msg.WebApiError'
      summary: Put File
      tags:
      - file
swagger: "2.0"
